/**
 * GET  /api/vault/items - List the caller's encrypted items
 * POST /api/vault/items - Create an item
 *
 * Authentication: session cookie (web) OR Bearer token (extension)
 *
 * Items are ciphertext to this route. The id is generated by the client because
 * it is bound into the ciphertext as additional authenticated data, so the
 * server accepting an id it did not choose is deliberate — see
 * packages/vault/src/items.js.
 *
 * Query parameters:
 *   ?since=<ISO timestamp>  only items changed since then (incremental sync)
 *   ?trash=1                the trash bin instead of the active vault
 */

import { NextResponse } from 'next/server';
import { corsHeaders, getAuthenticatedUser } from '@/lib/auth-helper';
import { validateItemPayload, MAX_BULK_ITEMS, MAX_PAGE_SIZE } from '@/lib/vault-validation';

export async function OPTIONS(request) {
  return new NextResponse(null, {
    status: 204,
    headers: corsHeaders(request, ['GET', 'POST', 'OPTIONS']),
  });
}

export async function GET(request) {
  const headers = corsHeaders(request, ['GET', 'POST', 'OPTIONS']);

  try {
    const { user, supabase } = await getAuthenticatedUser(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401, headers });
    }

    const { searchParams } = new URL(request.url);
    const since = searchParams.get('since');
    const wantsTrash = searchParams.get('trash') === '1';
    const limit = Math.min(Number(searchParams.get('limit')) || MAX_PAGE_SIZE, MAX_PAGE_SIZE);
    // A vault larger than one page was previously unreachable: the response was
    // capped and there was no way to ask for the rest.
    const offset = Math.max(Number(searchParams.get('offset')) || 0, 0);

    let query = supabase
      .from('vault_items')
      .select('id, type, ciphertext, iv, revision, deleted_at, created_at, updated_at')
      .eq('user_id', user.id)
      // updated_at alone is not unique -- an import writes thousands of rows in
      // the same instant -- and a non-deterministic order across pages drops
      // and repeats rows. id is the tiebreaker that makes paging total.
      .order('updated_at', { ascending: false })
      .order('id', { ascending: false })
      .range(offset, offset + limit - 1);

    query = wantsTrash ? query.not('deleted_at', 'is', null) : query.is('deleted_at', null);

    if (since) {
      const parsed = new Date(since);
      if (Number.isNaN(parsed.getTime())) {
        return NextResponse.json({ error: 'Invalid since timestamp' }, { status: 400, headers });
      }
      query = query.gt('updated_at', parsed.toISOString());
    }

    const { data, error } = await query;

    if (error) {
      console.error('Vault items fetch error:', error);
      return NextResponse.json({ error: 'Failed to fetch items' }, { status: 500, headers });
    }

    // `paged` tells a client that this server understands `offset`, so it can
    // safely ask for the next page. Without it a client cannot distinguish a
    // paging server from one that silently ignores the parameter and would
    // return the same first page forever.
    return NextResponse.json({ items: data || [], paged: true }, { headers });
  } catch (error) {
    console.error('Vault items API error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500, headers });
  }
}

/**
 * Body: { id, type, ciphertext, iv }
 */
/**
 * Create many items in one statement.
 *
 * `ignoreDuplicates` rather than a failed batch: an id that already exists is
 * what an interrupted import looks like on its second run, and the whole point
 * of carrying client-side ids is that re-running the same file resumes instead
 * of duplicating. A row that was skipped is reported as already-present, which
 * is what the single-item path's 409 means too.
 *
 * An id belonging to somebody else's row conflicts and is skipped, so a batch
 * can neither overwrite nor read another user's item.
 */
async function createManyItems({ body, user, supabase, headers }) {
  const items = body.items;

  if (items.length === 0) {
    return NextResponse.json({ items: [], created: 0, already: 0 }, { status: 201, headers });
  }
  if (items.length > MAX_BULK_ITEMS) {
    return NextResponse.json(
      { error: `At most ${MAX_BULK_ITEMS} items per request` },
      { status: 400, headers }
    );
  }

  // Validated before anything is written, so a bad row rejects the request
  // rather than leaving a partial batch behind.
  for (let i = 0; i < items.length; i++) {
    const invalid = validateItemPayload(items[i]);
    if (invalid) {
      return NextResponse.json({ error: `items[${i}]: ${invalid}` }, { status: 400, headers });
    }
  }

  const rows = items.map((item) => ({
    id: item.id,
    user_id: user.id,
    type: item.type,
    ciphertext: item.ciphertext,
    iv: item.iv,
  }));

  const { data, error } = await supabase
    .from('vault_items')
    .upsert(rows, { onConflict: 'id', ignoreDuplicates: true })
    .select('id, type, revision, created_at, updated_at');

  if (error) {
    console.error('Vault items bulk insert error:', error);
    return NextResponse.json({ error: 'Failed to create items' }, { status: 500, headers });
  }

  const created = data ?? [];
  return NextResponse.json(
    { items: created, created: created.length, already: rows.length - created.length },
    { status: 201, headers }
  );
}

export async function POST(request) {
  const headers = corsHeaders(request, ['GET', 'POST', 'OPTIONS']);

  try {
    const { user, supabase } = await getAuthenticatedUser(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401, headers });
    }

    const body = await request.json().catch(() => null);

    // A batch create. An import of a few thousand items was a few thousand
    // POSTs, which is minutes of round trips for work one statement can do.
    // The single-item shape below is unchanged, so older clients keep working.
    if (body && Array.isArray(body.items)) {
      return createManyItems({ body, user, supabase, headers });
    }

    const invalid = validateItemPayload(body);
    if (invalid) {
      return NextResponse.json({ error: invalid }, { status: 400, headers });
    }

    const { data, error } = await supabase
      .from('vault_items')
      .insert({
        id: body.id,
        user_id: user.id,
        type: body.type,
        ciphertext: body.ciphertext,
        iv: body.iv,
      })
      .select('id, type, revision, created_at, updated_at')
      .single();

    if (error) {
      // A duplicate id means the client already created this item — most often
      // a retry of a request that in fact succeeded.
      if (error.code === '23505') {
        return NextResponse.json({ error: 'Item already exists' }, { status: 409, headers });
      }
      console.error('Vault item insert error:', error);
      return NextResponse.json({ error: 'Failed to create item' }, { status: 500, headers });
    }

    return NextResponse.json({ item: data }, { status: 201, headers });
  } catch (error) {
    console.error('Vault items API error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500, headers });
  }
}
