/**
 * GET  /api/vault/items - List the caller's encrypted items
 * POST /api/vault/items - Create an item
 *
 * Authentication: session cookie (web) OR Bearer token (extension)
 *
 * Items are ciphertext to this route. The id is generated by the client because
 * it is bound into the ciphertext as additional authenticated data, so the
 * server accepting an id it did not choose is deliberate — see
 * packages/vault/src/items.js.
 *
 * Query parameters:
 *   ?since=<ISO timestamp>  only items changed since then (incremental sync)
 *   ?trash=1                the trash bin instead of the active vault
 */

import { NextResponse } from 'next/server';
import { corsHeaders, getAuthenticatedUser } from '@/lib/auth-helper';
import { validateItemPayload, MAX_PAGE_SIZE } from '@/lib/vault-validation';

export async function OPTIONS(request) {
  return new NextResponse(null, {
    status: 204,
    headers: corsHeaders(request, ['GET', 'POST', 'OPTIONS']),
  });
}

export async function GET(request) {
  const headers = corsHeaders(request, ['GET', 'POST', 'OPTIONS']);

  try {
    const { user, supabase } = await getAuthenticatedUser(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401, headers });
    }

    const { searchParams } = new URL(request.url);
    const since = searchParams.get('since');
    const wantsTrash = searchParams.get('trash') === '1';
    const limit = Math.min(Number(searchParams.get('limit')) || MAX_PAGE_SIZE, MAX_PAGE_SIZE);
    // A vault larger than one page was previously unreachable: the response was
    // capped and there was no way to ask for the rest.
    const offset = Math.max(Number(searchParams.get('offset')) || 0, 0);

    let query = supabase
      .from('vault_items')
      .select('id, type, ciphertext, iv, revision, deleted_at, created_at, updated_at')
      .eq('user_id', user.id)
      // updated_at alone is not unique -- an import writes thousands of rows in
      // the same instant -- and a non-deterministic order across pages drops
      // and repeats rows. id is the tiebreaker that makes paging total.
      .order('updated_at', { ascending: false })
      .order('id', { ascending: false })
      .range(offset, offset + limit - 1);

    query = wantsTrash ? query.not('deleted_at', 'is', null) : query.is('deleted_at', null);

    if (since) {
      const parsed = new Date(since);
      if (Number.isNaN(parsed.getTime())) {
        return NextResponse.json({ error: 'Invalid since timestamp' }, { status: 400, headers });
      }
      query = query.gt('updated_at', parsed.toISOString());
    }

    const { data, error } = await query;

    if (error) {
      console.error('Vault items fetch error:', error);
      return NextResponse.json({ error: 'Failed to fetch items' }, { status: 500, headers });
    }

    // `paged` tells a client that this server understands `offset`, so it can
    // safely ask for the next page. Without it a client cannot distinguish a
    // paging server from one that silently ignores the parameter and would
    // return the same first page forever.
    return NextResponse.json({ items: data || [], paged: true }, { headers });
  } catch (error) {
    console.error('Vault items API error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500, headers });
  }
}

/**
 * Body: { id, type, ciphertext, iv }
 */
export async function POST(request) {
  const headers = corsHeaders(request, ['GET', 'POST', 'OPTIONS']);

  try {
    const { user, supabase } = await getAuthenticatedUser(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401, headers });
    }

    const body = await request.json().catch(() => null);
    const invalid = validateItemPayload(body);
    if (invalid) {
      return NextResponse.json({ error: invalid }, { status: 400, headers });
    }

    const { data, error } = await supabase
      .from('vault_items')
      .insert({
        id: body.id,
        user_id: user.id,
        type: body.type,
        ciphertext: body.ciphertext,
        iv: body.iv,
      })
      .select('id, type, revision, created_at, updated_at')
      .single();

    if (error) {
      // A duplicate id means the client already created this item — most often
      // a retry of a request that in fact succeeded.
      if (error.code === '23505') {
        return NextResponse.json({ error: 'Item already exists' }, { status: 409, headers });
      }
      console.error('Vault item insert error:', error);
      return NextResponse.json({ error: 'Failed to create item' }, { status: 500, headers });
    }

    return NextResponse.json({ item: data }, { status: 201, headers });
  } catch (error) {
    console.error('Vault items API error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500, headers });
  }
}
